import numpy as np
import tensorflow as tf
from data_ingestion import RealWorldDataIngestion
from preprocessing import DataPreprocessor
from pipeline import DisinformationPipeline
from nn_models import (
    create_nlp_model,
    create_tabular_model,
    create_vision_model,
    create_meta_ensemble_model
)

def prepare_real_data(posts, preprocessor, heuristic_pipeline):
    """
    Takes raw live posts, runs them through the heuristic pipeline to get "pseudo-labels",
    and uses the preprocessor to convert them into neural network input tensors.
    """
    print("\nProcessing real-world data and generating heuristic labels...")

    # We will build the vocabulary for the NLP vectorizer using the headlines + content
    corpus = [p.get("headline", "") + " " + p.get("content", "") for p in posts]
    preprocessor.adapt_vectorizer(corpus)

    # Initialize lists to hold the formatted tensors
    X_text_list = []
    X_meta_list = []
    X_image_list = []
    y_pseudo_labels = []

    for idx, post in enumerate(posts):
        # 1. Run through the heuristic pipeline to get a pseudo-label (Weak Supervision)
        # This acts as our "teacher" before human fact-checkers step in.
        report = heuristic_pipeline.analyze_post(post)
        disinfo_prob = report["final_score"]["disinformation_probability"]

        # Binarize label for standard classification (Threshold at 0.5)
        pseudo_label = 1 if disinfo_prob > 0.5 else 0
        y_pseudo_labels.append(pseudo_label)

        # 2. Extract and format NLP features
        full_text = post.get("headline", "") + " " + post.get("content", "")
        text_tensor = preprocessor.process_text(full_text)
        X_text_list.append(text_tensor)

        # 3. Extract and format Tabular/Metadata features
        # We also pass the source reliability score calculated by the heuristic pipeline
        # to help the neural network learn which sources are bad.
        source_score = report["analysis"]["1_source_reliability"]["score"]
        meta_tensor = preprocessor.process_metadata(post.get("user_profile", {}), source_score)
        X_meta_list.append(meta_tensor)

        # 4. Extract and format Vision/Image features
        image_tensor = preprocessor.process_image(post.get("media_url", ""))
        X_image_list.append(image_tensor)

        if (idx + 1) % 5 == 0:
            print(f"  Processed {idx + 1}/{len(posts)} posts...")

    # Convert lists to NumPy arrays (which Keras requires)
    X_text = np.array(X_text_list)
    X_meta = np.array(X_meta_list)
    X_image = np.array(X_image_list)
    y = np.array(y_pseudo_labels)

    return X_text, X_meta, X_image, y

def main():
    print("=== Disinformation Detector: Real-World Training Run ===\n")

    # Step 1: Initialize components
    ingestion = RealWorldDataIngestion()
    preprocessor = DataPreprocessor()
    heuristic_pipeline = DisinformationPipeline()

    # Step 2: Fetch Live Data
    live_posts = ingestion.fetch_live_posts()

    if not live_posts:
        print("Error: Could not fetch live data. Ensure you have an internet connection.")
        return

    # Step 3: Prepare the Data
    X_text, X_meta, X_image, y_true = prepare_real_data(
        live_posts, preprocessor, heuristic_pipeline
    )

    print(f"\nData successfully prepared!")
    print(f"X_text shape: {X_text.shape}")
    print(f"X_meta shape: {X_meta.shape}")
    print(f"X_image shape: {X_image.shape}")
    print(f"y shape: {y_true.shape}")
    print(f"Balance of Disinformation (1) vs Trustworthy (0): {np.mean(y_true)*100:.1f}% positive labels generated by heuristic pipeline.")

    # Step 4: Build the Neural Networks
    print("\n--- Initializing Neural Network Meta-Ensemble ---")
    nlp_model = create_nlp_model()
    tabular_model = create_tabular_model()
    vision_model = create_vision_model()

    ensemble = create_meta_ensemble_model(nlp_model, tabular_model, vision_model)

    # Step 5: Train the Meta-Ensemble using Live Data!
    print("\n--- Starting Real-World Training Process ---")

    # We use a smaller batch size and no validation split if data is too small
    # just for demonstration purposes.
    batch_size = 8
    val_split = 0.2 if len(y_true) > 10 else 0.0

    history = ensemble.fit(
        x=[X_text, X_meta, X_image],
        y=y_true,
        epochs=3,
        batch_size=batch_size,
        validation_split=val_split,
        verbose=1
    )

    print("\n--- Real-World Training Complete ---")
    if 'val_accuracy' in history.history:
        print("Final Validation Accuracy: {:.2f}%".format(history.history['val_accuracy'][-1] * 100))
    else:
        print("Final Training Accuracy: {:.2f}%".format(history.history['accuracy'][-1] * 100))
    print("The system is now capable of continuously learning from real internet streams.")

if __name__ == "__main__":
    main()
